version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yacineniasse/isi-burger:latest
    container_name: isi-burger-app
    restart: unless-stopped
    environment:
      APP_ENV: local
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: isiburger
      DB_USERNAME: postgres
      DB_PASSWORD: passer
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: noreply@isiburger.com
      MAIL_FROM_NAME: "Isi Burger"
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - mailpit

  postgres:
    image: postgres:17
    container_name: isi-burger-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: isiburger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailpit:
    image: sha256:71a97aac6adb07fe3ba1f789094f5388b16bbf69a8b783343d2f816de5de3dec  # Image Mailpit avec hash sha256
    container_name: isi-burger-mailpit
    ports:
      - "8025:8025"  # Interface web Mailpit
      - "1025:1025"  # SMTP
    environment:
      - MAILPIT_SMTP_BIND=0.0.0.0:1025
      - MAILPIT_HTTP_BIND=0.0.0.0:8025
    restart: unless-stopped

volumes:
  postgres-data:
